#+TODO: IDEA TODO INFO INPROGRESS DONE

* IDEA zmodyfikowac nadawanie tak aby pakiety nie byly niepotrzebnie kolejkowane 
** PROBLEM brak pakietow w kolejce
Jesli nie skolejkuje sie na poczatku kilku pakietow to nie ma pewnosci ze nadanie bitu sie uda gdyz rozmowa moze sie w kazdej chwili zakonczyc. Jesli nie uda sie przeslac tego jednego bitu to cala paczka idzie do piachu
Wykrywanie takiej sytuacji po stronie nadawcy nie jest zadnym sensownym rozwiazaniem

* IDEA Minimalna liczba pakietow w danym strumieniu pomiedzy bitami - unikanie pomylek
  W strumieni musi uplynac przynajmniej X pakietow zanim zostanie nadany bit. To moze pozwolic na unikniecie przypadkowych przeklaman, ale wymaga kolejkowanie pakietow nawet jesli strumien jest nieoblusgiwany

* IDEA Pobranie pakietu z kolejki, wykonanie kopii i akceptacja - obrabianie w oddzielnym watku - speed gain

* IDEA Sekwencja przenosząca bit musi zaczynac sie od pakietu ktorego SEQ podzielne przez np. 5
* IDEA Rozmiar okna - ilosc bitow ktore nie wymagaja potwierdzenia
* IDEA Potwierdzenie - powielenie pakietu SEQ parz - OK SEQ nparz - NOK

* TODO Protokol potwierdzen i powtorzen
* TODO W dokumentacji opisac ramke SDP, wkleic PELNA z Wiresharka

* TODO Zmodyfikowac pola w pliku konfiguracyjnym
* TODO Komunikaty SIP korzystaja z wielu kolejek? A po co?
  Wydaje sie ze jednak jest jedna kolejka dla komunikatow od-nadajnika i jedna dla od-odbiornika wiec ok.

* INFO Co mozna zrobic z pakietami RTP?
** Powielic
** Zgubic
** Opoznic
** Przyspieszyc
** Zamienic kolejnosc <-- to tez jest opoznienie bo trzeba dysponowac dwoma pakietami

* INFO Schemat dzialania:
  1. nadawca wysyla sekewencje A informujaca o paczce danych
  2. nadawca rozpoczyna wysylanie paczki danych
  3. odbiornik potwierdza odebranie paczki

* Zminimalizowac liczb watkow - modul sip::inout moze byc obsluzony jednym
  Teoretycznie obie kolejki mozna obsluzyc select'em. Nie ma wtedy tej brzydkiej globalnej mapy definiujacej kto jest kto. Komunikatow SIP chyba tez nei ma tak duzo zeby potrzebny byl oddzielny watek
 
* PROBLEM co zrobic jesli zostanie nadany bit, a potwierdzenie nie przyjdzie bo rozmowa zostala zakonczona i nie ma pakietow w kolejce?
** W odbiorniku przynajmniej jeden pakiet - potwierdzenie przez powielenie


* TODO [1] Modul sender i revceiver ktore akceptuja pakiety bez wplywania na opznienia
